AWSTemplateFormatVersion: '2010-09-09'

Description:
  services about application layer

Resources:

  SGbastionHost:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection from ssh
      VpcId:
        Fn::ImportValue:
          !Sub "network-stack-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
    
  SGALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection from http port 80
      VpcId:
        Fn::ImportValue:
          !Sub "network-stack-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  SGwebserver:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection from alb
      VpcId:
        Fn::ImportValue:
          !Sub "network-stack-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !GetAtt SGALB.GroupId
  
  SGdatabases:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection from web server
      VpcId:
        Fn::ImportValue:
          !Sub "network-stack-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt SGwebserver.GroupId
        